language: php

php:
    - 8.0

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --prefer-source

script:
    - vendor/bin/phpunit
